### ISSUE TITLE
Output Structure

### ISSUE THREAD

**Issue by daviddalpiaz** [coatless/assignr#7]
Specify via YAML header?

**Comment by coatless** [comment]
@daviddalpiaz something along the lines of:

```yaml
output: 
  assignr::gen_hw: 
    assign: yes
    soln: yes
    output_dir: "path/to/dir"
```

Sound good?
